deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJGU3ZDhlNzk4LTZlNmYtNGEyMi05NGQzLTI0NDA1NzM4MjM4MwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYglOkCd75AqUHZ0bjdkwfkIULzF4S5sEYWySaHK93w77o"