deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgENdGVzdC5weXBpLm9yZwIkODEzNzhhMjMtYmFhZS00MTZjLWJiY2QtOWFiODI3NTM2NmQ5AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiBLT6gLXholWb9tYQaFqgCM2Ecu4gPFMYf_00For-4Msg"